version: "3.8"

services:
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=node
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
